import { MockSession, MockRun } from './types';

export const mockSessions: MockSession[] = [
  {
    session_id: 'session-orchestrator-main',
    name: 'orchestrator-main',
    agent_name: 'orchestrator',
    status: 'finished' as const,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    project_dir: '/projects/data-pipeline',
    parent_session_id: null as string | null,
    runCount: 3,
    latestRunStatus: 'completed' as const,
  },
  {
    session_id: 'session-child-researcher',
    name: 'child-researcher',
    agent_name: 'researcher',
    status: 'finished' as const,
    created_at: new Date(Date.now() - 1.8 * 60 * 60 * 1000).toISOString(),
    project_dir: '/projects/data-pipeline',
    parent_session_id: 'session-orchestrator-main',
    runCount: 1,
    latestRunStatus: 'completed' as const,
  },
  {
    session_id: 'session-child-coder',
    name: 'child-coder',
    agent_name: 'coder',
    status: 'finished' as const,
    created_at: new Date(Date.now() - 1.7 * 60 * 60 * 1000).toISOString(),
    project_dir: '/projects/data-pipeline',
    parent_session_id: 'session-orchestrator-main',
    runCount: 2,
    latestRunStatus: 'completed' as const,
  },
  {
    session_id: 'session-data-pipeline',
    name: 'data-pipeline-worker',
    agent_name: 'data-processor',
    status: 'running' as const,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    project_dir: '/projects/analytics',
    parent_session_id: null as string | null,
    runCount: 2,
    latestRunStatus: 'running' as const,
  },
  {
    session_id: 'session-research-agent',
    name: 'research-analysis',
    agent_name: 'researcher',
    status: 'finished' as const,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    project_dir: '/projects/research',
    parent_session_id: null as string | null,
    runCount: 1,
    latestRunStatus: 'completed' as const,
  },
];

export const mockRuns: MockRun[] = [
  {
    run_id: 'run-001',
    session_id: 'session-orchestrator-main',
    type: 'start_session' as const,
    status: 'completed' as const,
    prompt:
      'Orchestrate the data pipeline for processing customer analytics. Coordinate with child agents for data extraction, transformation, and loading.',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 2 * 60 * 60 * 1000 + 5000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 60 * 60 * 1000 + 323000).toISOString(),
    runner_id: 'runner-abc123def',
    agent_name: 'orchestrator',
    runNumber: 1,
    events: [
      { type: 'session_start', timestamp: '10:00:00', summary: 'Session initialized' },
      { type: 'tool_call', timestamp: '10:00:45', summary: 'start_agent_session (child-1)' },
      { type: 'tool_call', timestamp: '10:00:52', summary: 'start_agent_session (child-2)' },
      {
        type: 'assistant',
        timestamp: '10:01:02',
        summary: 'Started 2 child agents for parallel processing...',
      },
      { type: 'tool_result', timestamp: '10:03:15', summary: 'child-1 completed extraction' },
      { type: 'tool_result', timestamp: '10:04:30', summary: 'child-2 completed transformation' },
      { type: 'session_stop', timestamp: '10:05:23', summary: 'Session completed successfully' },
    ],
  },
  {
    run_id: 'run-002',
    session_id: 'session-orchestrator-main',
    type: 'resume_session' as const,
    status: 'completed' as const,
    prompt: 'Resume to process callback from child agent with aggregated results.',
    created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000 + 3000).toISOString(),
    completed_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000 + 135000).toISOString(),
    runner_id: 'runner-abc123def',
    agent_name: 'orchestrator',
    runNumber: 2,
    events: [
      { type: 'session_resume', timestamp: '10:30:00', summary: 'Session resumed (callback trigger)' },
      { type: 'user', timestamp: '10:30:01', summary: 'Callback received from child-1' },
      { type: 'assistant', timestamp: '10:30:15', summary: 'Processing aggregated results...' },
      { type: 'session_stop', timestamp: '10:32:15', summary: 'Session paused for next callback' },
    ],
  },
  {
    run_id: 'run-003',
    session_id: 'session-orchestrator-main',
    type: 'resume_session' as const,
    status: 'completed' as const,
    prompt: 'Final aggregation and report generation.',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1 * 60 * 60 * 1000 + 2000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 60 * 60 * 1000 + 180000).toISOString(),
    runner_id: 'runner-xyz789abc',
    agent_name: 'orchestrator',
    runNumber: 3,
    events: [
      { type: 'session_resume', timestamp: '11:00:00', summary: 'Session resumed for final processing' },
      { type: 'tool_call', timestamp: '11:00:30', summary: 'generate_report' },
      { type: 'tool_result', timestamp: '11:02:00', summary: 'Report generated successfully' },
      {
        type: 'assistant',
        timestamp: '11:02:30',
        summary: 'Pipeline completed. Report available at /reports/analytics-2024.pdf',
      },
      { type: 'session_stop', timestamp: '11:03:00', summary: 'Session finished' },
    ],
  },
  {
    run_id: 'run-004',
    session_id: 'session-data-pipeline',
    type: 'start_session' as const,
    status: 'completed' as const,
    prompt: 'Initialize data pipeline worker for ETL processing.',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 45 * 60 * 1000 + 2000).toISOString(),
    completed_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    runner_id: 'runner-def456ghi',
    agent_name: 'data-processor',
    runNumber: 1,
    events: [
      { type: 'session_start', timestamp: '11:15:00', summary: 'Pipeline worker started' },
      { type: 'tool_call', timestamp: '11:15:30', summary: 'connect_database' },
      { type: 'tool_result', timestamp: '11:15:35', summary: 'Database connected' },
      { type: 'assistant', timestamp: '11:20:00', summary: 'ETL phase 1 complete' },
      { type: 'session_stop', timestamp: '11:30:00', summary: 'Awaiting next batch' },
    ],
  },
  {
    run_id: 'run-005',
    session_id: 'session-data-pipeline',
    type: 'resume_session' as const,
    status: 'running' as const,
    prompt: 'Process incoming data batch from queue.',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 10 * 60 * 1000 + 1000).toISOString(),
    completed_at: null,
    runner_id: 'runner-def456ghi',
    agent_name: 'data-processor',
    runNumber: 2,
    events: [
      { type: 'session_resume', timestamp: '11:50:00', summary: 'Processing new batch' },
      { type: 'tool_call', timestamp: '11:50:15', summary: 'fetch_batch_data' },
      { type: 'tool_result', timestamp: '11:50:20', summary: '1,247 records retrieved' },
      { type: 'assistant', timestamp: '11:51:00', summary: 'Transforming records...' },
    ],
  },
  {
    run_id: 'run-006',
    session_id: 'session-research-agent',
    type: 'start_session' as const,
    status: 'completed' as const,
    prompt: 'Research and analyze market trends for Q4 report.',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 5 * 60 * 60 * 1000 + 3000).toISOString(),
    completed_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    runner_id: 'runner-ghi789jkl',
    agent_name: 'researcher',
    runNumber: 1,
    events: [
      { type: 'session_start', timestamp: '07:00:00', summary: 'Research session started' },
      { type: 'tool_call', timestamp: '07:01:00', summary: 'web_search (market trends 2024)' },
      { type: 'tool_result', timestamp: '07:01:30', summary: '15 relevant sources found' },
      { type: 'assistant', timestamp: '07:15:00', summary: 'Analysis complete. Key findings documented.' },
      { type: 'session_stop', timestamp: '07:30:00', summary: 'Research session finished' },
    ],
  },
  // Child session runs
  {
    run_id: 'run-007',
    session_id: 'session-child-researcher',
    type: 'start_session' as const,
    status: 'completed' as const,
    prompt: 'Research data sources for pipeline integration.',
    created_at: new Date(Date.now() - 1.8 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1.8 * 60 * 60 * 1000 + 2000).toISOString(),
    completed_at: new Date(Date.now() - 1.6 * 60 * 60 * 1000).toISOString(),
    runner_id: 'runner-child-001',
    agent_name: 'researcher',
    runNumber: 1,
    events: [
      { type: 'session_start', timestamp: '10:12:00', summary: 'Child researcher started' },
      { type: 'tool_call', timestamp: '10:12:30', summary: 'search_apis' },
      { type: 'tool_result', timestamp: '10:13:00', summary: 'Found 5 compatible APIs' },
      { type: 'assistant', timestamp: '10:20:00', summary: 'Research complete, sending results to parent' },
      { type: 'session_stop', timestamp: '10:24:00', summary: 'Child session finished' },
    ],
  },
  {
    run_id: 'run-008',
    session_id: 'session-child-coder',
    type: 'start_session' as const,
    status: 'completed' as const,
    prompt: 'Implement data transformation module.',
    created_at: new Date(Date.now() - 1.7 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1.7 * 60 * 60 * 1000 + 1500).toISOString(),
    completed_at: new Date(Date.now() - 1.4 * 60 * 60 * 1000).toISOString(),
    runner_id: 'runner-child-002',
    agent_name: 'coder',
    runNumber: 1,
    events: [
      { type: 'session_start', timestamp: '10:18:00', summary: 'Child coder started' },
      { type: 'tool_call', timestamp: '10:19:00', summary: 'read_file (schema.json)' },
      { type: 'tool_result', timestamp: '10:19:10', summary: 'Schema loaded' },
      { type: 'tool_call', timestamp: '10:25:00', summary: 'write_file (transformer.py)' },
      { type: 'assistant', timestamp: '10:30:00', summary: 'Transformation module complete' },
      { type: 'session_stop', timestamp: '10:36:00', summary: 'Waiting for review' },
    ],
  },
  {
    run_id: 'run-009',
    session_id: 'session-child-coder',
    type: 'resume_session' as const,
    status: 'completed' as const,
    prompt: 'Apply review feedback and finalize module.',
    created_at: new Date(Date.now() - 1.3 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1.3 * 60 * 60 * 1000 + 1000).toISOString(),
    completed_at: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
    runner_id: 'runner-child-002',
    agent_name: 'coder',
    runNumber: 2,
    events: [
      { type: 'session_resume', timestamp: '10:42:00', summary: 'Resumed for feedback' },
      { type: 'user', timestamp: '10:42:05', summary: 'Feedback: Add error handling' },
      { type: 'tool_call', timestamp: '10:45:00', summary: 'edit_file (transformer.py)' },
      { type: 'assistant', timestamp: '10:48:00', summary: 'Error handling added, module finalized' },
      { type: 'session_stop', timestamp: '10:48:30', summary: 'Child session completed' },
    ],
  },
];
