"""
Pydantic validation schemas for Agent Orchestrator MCP Server

Note: Uses session_id (coordinator-generated) per ADR-010.
Session IDs are generated by the coordinator, not validated by the MCP server.
"""

from typing import Optional
from pydantic import BaseModel, ConfigDict, Field

from types_models import ResponseFormat


# Base schema for response format
class ResponseFormatField(BaseModel):
    """Base class with response format field"""
    response_format: ResponseFormat = Field(
        default=ResponseFormat.MARKDOWN,
        description="Output format: 'markdown' for human-readable or 'json' for machine-readable"
    )


# Base schema for project directory
class ProjectDirField(BaseModel):
    """Base class with project directory field"""
    project_dir: Optional[str] = Field(
        default=None,
        description="Optional project directory path (must be absolute path). Only set when instructed to set a project dir!"
    )


# Schema for list_agent_blueprints tool
class ListAgentBlueprintsInput(ResponseFormatField):
    """Input schema for list_agent_blueprints tool"""
    pass


# Schema for list_agent_sessions tool
class ListAgentSessionsInput(ResponseFormatField):
    """Input schema for list_agent_sessions tool"""
    pass


# Schema for start_agent_session tool
# Note: session_id is generated by coordinator (ADR-010), not provided by client
class StartAgentSessionInput(ProjectDirField):
    """Input schema for start_agent_session tool"""
    agent_blueprint_name: Optional[str] = Field(
        default=None,
        alias="agent_name",
        description="Name of agent blueprint to use for this session (optional for generic sessions)"
    )
    prompt: str = Field(
        min_length=1,
        description="Initial prompt or task description for the agent session"
    )
    async_: bool = Field(
        default=False,
        alias="async",
        description="Run agent in background (fire-and-forget mode). When true, returns immediately with session info. Use get_agent_session_status to poll for completion."
    )

    model_config = ConfigDict(populate_by_name=True)


# Schema for resume_agent_session tool
class ResumeAgentSessionInput(BaseModel):
    """Input schema for resume_agent_session tool"""
    session_id: str = Field(
        min_length=1,
        description="ID of the existing session to resume (coordinator-generated)"
    )
    prompt: str = Field(
        min_length=1,
        description="Continuation prompt or task description for the resumed session"
    )
    async_: bool = Field(
        default=False,
        alias="async",
        description="Run agent in background (fire-and-forget mode). When true, returns immediately with session info. Use get_agent_session_status to poll for completion."
    )

    model_config = ConfigDict(populate_by_name=True)


# Schema for delete_all_agent_sessions tool
class DeleteAllAgentSessionsInput(BaseModel):
    """Input schema for delete_all_agent_sessions tool"""
    pass


# Schema for get_agent_session_status tool
class GetAgentSessionStatusInput(BaseModel):
    """Input schema for get_agent_session_status tool"""
    session_id: str = Field(
        min_length=1,
        description="ID of the session to check status for"
    )
    wait_seconds: int = Field(
        default=0,
        ge=0,
        le=300,
        description="Number of seconds to wait before checking status (default: 0). Useful for polling long-running agents with longer intervals to reduce token usage."
    )


# Schema for get_agent_session_result tool
class GetAgentSessionResultInput(BaseModel):
    """Input schema for get_agent_session_result tool"""
    session_id: str = Field(
        min_length=1,
        description="ID of the session to retrieve result from (coordinator-generated)"
    )
